config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  root 'home#index'

  get 'home/index'

  get 'home/play'
  post 'home/create_game', to: 'home#create_game'
  post 'home/join_game', to: 'home#join_game'
  post 'home/play_card', to: 'home#play_card'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_player!



   def index
    @current_player = current_player
    @game = Game.all.first || Game.create!
    find_players 
  end #index

  def join_game
    @current_player = current_player
   # byebug
    @game = Game.all.first || Game.create!
    find_players
    if @players.include? @current_player
      flash[:alert] = "You already joined!"
    else
      @game_player = GamePlayer.find_or_create_by!(game: @game, player: @current_player)
    end
    redirect_to :home_index
  end



  def play
    @current_player = current_player
    if GamePlayer.find_by(player: @current_player)
      @game = GamePlayer.find_by(player: @current_player).game
      find_players
    else 
      redirect_to :home_index
    end
  end #play

  def create_game 
    @game = Game.all.first || Game.create!
    reset_game
    @current_player = current_player
    if params[:players]
      find_players_by_params
    end
    @players.each do |player|
      @game_player = GamePlayer.create!(game: @game, player: player)
    end
    @deck = Deck.all.first || Deck.create!
    @deck.update!(game: @game)
    @deck.build_deck
    init_players
    @trick = Trick.create!(game: @game)
    redirect_to :home_play
  end #create

  def play_card
    @card = Card.find(params[:card])
    @current_player = current_player
    @game = Game.find(params[:game])
    find_players
    if (@game.player_to_play(@players)==@current_player) && (@current_player.hand.cards.count + @game.round == 10)
      @card.update!(trick: @game.trick, hand: nil)
      @game.to_next_player
      @game.save
    else
      flash[:alert] = 'Not your turn!'
      #byebug
    end
    #byebug
    redirect_to :home_play
  end



private


  
  def find_players
    @players = []
    @player_ids = GamePlayer.where(game_id: @game.id).distinct.pluck(:player_id) || []
    @player_ids.each do |player_id|
      @players << Player.find(player_id)
    end  
  end #find_players

  def find_players_by_params
    @players = []
    params[:players].each do |player_id|
      @players << Player.find(player_id)
    end
  end

  def init_players
    @players.each do |player|
      #hand = Hand.new(player: player)
      hand = Hand.find_or_create_by!(player: player)
      @deck.deal_to(hand)
      hand.save
      player.save
    end
  end #init_players

  def destroy_player_hands
    find_players
    @players.each do |player|
      if player.hand
        player.hand.destroy!
      end
    end
  end

  def destroy_game_players
    find_players
    @players.each do |player|
      player.game_player.destroy!  
    end 
  end 

  def reset_game
    @game.update!(round: 0, next_player:1)
    if @game.trick
      @game.trick.destroy!
    end
    destroy_player_hands
    destroy_game_players
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_human_player.html.erb
  <div class="row small-up-2 medium-up-3 large-up-5">
    <h2>Mein Blatt:</h2>   
  </div>
  <div class="row small-up-2 medium-up-3 large-up-5 human-player">
    <% @current_player.hand.cards.each do |card| %>
      <div class="column column-block">
        
        <div class="card play-card">
          <img src="/assets/cards/<%= card.name %>.png">
          <div class="card-section">
            <%=link_to "Karte spielen", home_play_card_path(card: card, game: @game), method: :post, class: "button button-primary" %>
          </div>
        </div>
      
      </div>
    <% end %>
  </div>

app/views/home/_table.html.erb
<div class="row small-up-2 medium-up-3 large-up-5">
    <h2>Spieltisch:</h2>   
</div>
<div class="row small-up-2 medium-up-3 large-up-5 play-table">
  <% @game.trick.cards.each do |card| %>
    <div class="column column-block">
      <div class="card play-card">
        <div class="card-image float-center">
          <img src="/assets/cards/<%= card.name %>.png">
        </div>
        <div class="card-section float-center">
          Trick-Karte
        </div>
      </div>
    </div>
  <% end %>
</div>

  

app/views/home/_table_links.html.erb
<div class="row small-up-2 medium-up-3 large-up-5 table-links">
	<%= link_to "Neues Spiel", home_create_game_path(players: @players, game: @game), method: :post, class: "button button-primary" %>
	<%=	link_to "Tisch verlassen!", :home_index, class: "button primary" %>
</div>

app/views/home/index.html.erb
<% content_for :title, "Doppelkopf" %>

  <div class="row">
    <div class="large-12 columns">
      <h1>Doppelkopf</h1>
      <p>Warte auf Mitspieler...</p>


      	<% @players.each do |player| %>
      		<p>Player : <%=player.email %> </p>
      	<% end %>

		<%=link_to "Join Game", home_join_game_path, method: :post, class: "button button-primary" %>



    </div>
    <%=link_to "Play!", home_create_game_path(players: @players), method: :post, class: "button button-primary" %>
  </div>
 
 
 <%=@player1%>
 <%=@player2%>
 <%=@player3%>
 <%=@player4%>

app/views/home/play.html.erb
<% content_for :title, "Doppelkopf" %>
<div class="grid-x">
  	<div class="cell">
		<h1>Doppelkopf</h1>
   	</div>
	<div class="cell">
		<%= render partial: 'table' %>
	</div>
	<div class="cell">
		<%= render partial: 'human_player' %>
		
	</div>
	<div class="cell">
		<%= render partial: 'table_links' %>
	</div>
</div>