config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  root 'home#index'

  get 'home/index'

  get 'home/play'
  post 'home/create_game', to: 'home#create_game'
  post 'home/join_game', to: 'home#join_game'
  post 'home/play_card', to: 'home#play_card'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>



<% flash.each do | name, message | %>
  <%= content_tag :div, class: "callout #{name}", :data => { :closable => 'slide-out-right' }  do -%>
    <%= message %>
    <%= link_to('', html_options = {:"data-label" => "Dismiss alert" , :"data-close" => "data-close" }, class: "close-button") do-%>
      <span aria-hidden="true">&times;</span>
    <% end -%>
   <% end -%>
<% end -%>

app/views/layouts/_navigation.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Doppelkopf</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
		<%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if player_signed_in? %>
    <li><%= link_to 'Profile', edit_player_registration_path %></li>
    <li><%= link_to 'Log out', destroy_player_session_path, method: :delete %></li>
<% else %>
    <li><%= link_to 'Log In', new_player_session_path %></li>
    <li><%= link_to 'Sign Up', new_player_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Doko" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Doko" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>